export const hsEmploymentRoles = [
  { value: "accounting", label: "Accounting" },
  { value: "administrative", label: "Administrative" },
  { value: "business_development", label: "Business Development" },
  { value: "communications", label: "Communications" },
  { value: "consulting", label: "Consulting" },
  { value: "customer_service", label: "Customer Service" },
  { value: "design", label: "Design" },
  { value: "education", label: "Education" },
  { value: "engineering", label: "Engineering" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "finance", label: "Finance" },
  { value: "health_professional", label: "Health Professional" },
  { value: "human_resources", label: "Human Resources" },
  { value: "information_technology", label: "Information Technology" },
  { value: "legal", label: "Legal" },
  { value: "marketing", label: "Marketing" },
  { value: "operations", label: "Operations" },
  { value: "product", label: "Product" },
  { value: "project_management", label: "Project Management" },
  { value: "public_relations", label: "Public Relations" },
  { value: "quality_assurance", label: "Quality Assurance" },
  { value: "real_estate", label: "Real Estate" },
  { value: "recruiting", label: "Recruiting" },
  { value: "research", label: "Research" },
  { value: "sales", label: "Sales" },
  { value: "support", label: "Support" },
  { value: "retired", label: "Retired" },
  { value: "other", label: "Other" },
];
